[project]
name = "html-table-scraping"
version = "0.1.0"
description = "A simple module that turns HTML tables into Pandas DataFrames."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "Apache-2.0"}
dependencies = [
    "beautifulsoup4>=4.12",
    "ipython>=8.0",
    "pandas>=2.0",
    "requests>=2.31",
    "lxml>=4.9",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
